toll-free-data:
  dates:
    - year: 2013
      month: 1
      days: [ 1 ]
    - year: 2013
      month: 3
      days: [ 28, 29 ]
    - year: 2013
      month: 4
      days: [ 28 ]
    - year: 2013
      month: 5
      days: [ 1, 8, 9 ]
    - year: 2013
      month: 7
      days: [ 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30 ]
    - year: 2013
      month: 11
      days: [ 1 ]
    - year: 2013
      month: 12
      days: [ 24, 25, 26, 31 ]